apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakV3TWpNeQpNakl4TXpkYUZ3MDBNakV3TWpNeU1qSXhNemRhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDbXh1REZZT3o2RWZ1MVdzRHpvRDhDdW5NSU5tc2Y4WWgrYU5rQzBTazhVR1Mzdy9zZwpHRjhJU04yM2NJVHNZL2JyYldBeUdvbUdweEZmSUVsWVZqQkliMnAwZXYrWnhZZW9VYWxVUnhOb3E1eCtRcjh1ClVRQ29hTmR2UVpsMVcwbE1YVVZNUnEwUExuUmdNdU1NZ3Z5MEtDcHMvaVVHcXBBeXg0dFFBK0lDTVkwSjl6eW0KMDZsMjJtMVVQL3ZFZjZaV0o4bThPNlMwOE53SE9hUHlyYWpMVitXWENFNithcW91MDFNNGUxSjFTVjlBd0padgpNMUVJWEhhR0N3YzhDZTZldXJCbXBXaXRyT2pDQ3lMT2dxRUdnZks0NFh3Y2RhT25FdWRYM0tWUUpRRHQvNFhmCjdZYzhkbStBNjJKY2wvUHlUcGdBbU5EVjBLemxtM0RGdVlWSEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNrQ3NDdUtZL255bVJnRVp2SgpqZmxGbzJVTk1qQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFwTXJKa294MnRHOGN4ekpLNnN0ZjZOYlc4SURLCnd0UlRlVGdlRk5SV1dFN0ZOKzFGQTU1WnRIUU5MdndydzJsZ05kVlFCS2Rrc1crd0FsWEN6NTFaRU5KOVZsK3oKS0VOZGdBaTJJbXlpK3pzTnJzSFIzM01Uc3RCOFZpb0x4UEtpM1dxN0ovMFpBMDN4a0lUdUR2blo4U3UxRnQ2SQpCKzV1Ri9XTGVJanpySFI3NHdnemQrQUN5anhQNlpUNXg4Zkd3WDRodUZQWWlPNzZnYTFIaTdtQTFTTlIvbzVhClNuN0pvbjZ3WnFSK0JGdXRMSHRZTUdRWFhCOUZhTXpvdjRjYll6VkVPMVg2OHVPTzk1LzlzU29TR0Q4RHI2WE0KOVZORVNnbEl6d21mUkx0Y1ExYVV4RHJRdERrNjNJU25GdDBZV3NsWlMrdTZKRFgzdWxLRmQ5OXJldz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://0d664119-26a5-4e94-9360-fcdb2f361313.k8s.ondigitalocean.com
  name: do-nyc3-k8s
contexts:
- context:
    cluster: do-nyc3-k8s
    user: do-nyc3-k8s-admin
  name: do-nyc3-k8s
current-context: do-nyc3-k8s
users:
- name: do-nyc3-k8s-admin
  user:
    token: dop_v1_b137f471c70e30ddbf431aea9dd31a9232975c025cb36e2da09c47d1c7fbfaf8
